name: Java CI

on:
  push:
  pull_request:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build --no-daemon
      
      
  codestyle:
    name: Code Style checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            reporter: 'github-pr-check'
            tool_name: 'reviewdog'
